### ISSUE TITLE
[Ticket 0397]: Add scaled equipment to hub Merchant Buy

### ISSUE THREAD

**Issue by furiaz** [furiaz/MMOPartySimulator#482]
## What will happen
Add the new level 15 and level 20 prototype equipment from Ticket 0395 to the Harbor Union Bastion Merchant Buy stock, and add min/max level requirement filtering to Merchant Buy search.

## What will change
- Extend the fixed prototype Merchant Buy stock with the new scaled weapons, offhands, and armor items.
- Keep the Merchant stock fixed and prototype-only; no drop table, quest reward, crafting, rarity, affix, durability, or dynamic shop changes.
- Extend Merchant Buy filtering with optional minimum and maximum item level requirement filters in game logic.
- Add matching React controls to the Merchant Buy panel.
- Update focused merchant tests for stock, pricing, filters, and purchase behavior.

## Objectives
- Make level 15 and level 20 prototype gear purchasable from the hub Merchant for testing and progression inspection.
- Let the player narrow Merchant Buy results to relevant level bands.
- Preserve existing item/equipment validation and class compatibility rules.

## Goals
- Hub Merchant includes the scaled equipment added by Ticket 0395.
- Search filters can show items by minimum and maximum level requirement.
- Existing group, secondary, and party-compatible filters continue to work together with level range filters.

## Success criteria
- New level 15/20 equipment appears in Merchant Buy stock.
- Min/max level filters work independently and when combined with existing filters.
- Underlying purchase validation still rejects non-stock items and invalid merchants.
- Merchant tests and full build pass.

## GDD/GTD alignment
- Aligns with GDD current prototype hub Merchant supporting fixed prototype buy stock for selected equipment, consumables, and skill books.
- Aligns with GTD by keeping merchant stock and filtering rules in `client/src/game/merchant.ts` while React only displays and controls filters.
- Does not implement full shop economy, dynamic stock, selling, crafting, or production item economy.

## Out of scope
- No dynamic merchant inventory.
- No price economy overhaul.
- No item stat rebalance.
- No quest reward, enemy drop, crafting, upgrade, affix, rarity, durability, or visual equipment changes.
- No protected documentation edits.

## Implementation notes
- Reuse existing Merchant Buy stock entries and group filters.
- Add new items to the appropriate existing groups: weapons, offhands, cloth, leather, mail, and plate.
- Use straightforward prototype prices by level and slot so economy can be tuned later.
- Treat missing item `levelRequirement` as level 0 for filter purposes.
- Keep level filter parsing and presentation in React; keep filter behavior in game logic.

## Verification plan
- Run merchant-focused tests.
- Run item/equipment/stat tests touched by the dependent equipment definitions if needed.
- Run full test suite.
- Run production build.
- Run diff whitespace check.

### Predicted Behavior
The hub Merchant offers the new level 15 and level 20 prototype gear for direct testing. Merchant Buy can be filtered to show specific level bands while retaining group, subtype, and party compatibility filters.

### Risks / Flaws
The stock list will become large, which makes filtering more important. Prices are prototype values and may need economy tuning later, but this ticket should not expand into a full merchant economy.

### Cleaner Structure
Keep stock and filtering in `merchant.ts`, add only small UI state/controls in `App.tsx`, and avoid new systems or abstractions.

### Required Plan Changes
Keep current level 10 stock behavior and all non-merchant acquisition unchanged. Do not add unrelated equipment that was not part of Ticket 0395.

### Final Reviewed Plan
Add Ticket 0395 equipment to fixed hub Merchant Buy stock, add min/max level requirement filters to merchant game logic and UI, update focused tests, and leave documentation/protected docs for the companion documentation ticket.

**Comment by furiaz** [comment]
Implementation complete for Ticket 0397.

Main files changed:
- `client/src/game/merchant.ts`: added Ticket 0395 level 15/20 equipment to fixed Merchant Buy stock and added min/max level requirement filtering.
- `client/src/App.tsx`: added Merchant Buy min/max level filter inputs.
- `client/src/App.css`: styled the level filter controls in the existing Merchant Buy filter row.
- `client/src/game/merchant.test.ts`: added coverage for scaled stock entries, prices, purchases, party-compatible filtering, and level range filtering.

Verification performed:
- `npm test -- merchant.test.ts items.test.ts equipmentSystem.test.ts stats.test.ts` passed: 4 files, 58 tests.
- `npm test` passed: 75 files, 986 tests.
- `npm run build` passed.
- After final cleanup, `npm test -- merchant.test.ts` passed: 18 tests.
- After final cleanup, `npm run build` passed.
- `git diff --check` passed with only existing CRLF normalization warnings.

Scope notes:
- Kept this to fixed hub Merchant Buy stock and filters.
- Did not add dynamic stock, drop tables, quest rewards, crafting, selling, or economy tuning beyond prototype stock prices.
- Did not edit protected documentation.
